spring.application.name=Url-Shortner-sb

# MySQL Database Configuration (Defaults for local run, overridden by Docker Compose)
server.port=9090
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/urlshortnerdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate JPA Configuration
spring.jpa.hibernate.ddl-auto=update

# Show SQL Queries in the Console (Optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Include the secrets profile to load application-secrets.properties
spring.profiles.include=secrets
management.endpoints.web.exposure.include=health,metrics
# Log incoming web requests and routing
logging.level.org.springframework.web=DEBUG

# Log Spring Security filter chain decisions
logging.level.org.springframework.security=DEBUG